hw7
lyubavinaju/IuliiaLiubavina pull request #7
Opened 2021-11-24 21:10 UTC by lyubavinaju

2021-11-25 17:54 UTC, cold-flame requested changes

2021-11-25 17:54 UTC, cold-flame commented on src/main/java/com/epam/tc/hw7/JdiSite.java
> +    @Css("form")
In JdiSite class need to declare variable WebPage class

2021-11-25 17:54 UTC, cold-flame commented on src/main/java/com/epam/tc/hw7/pages/MetalsColorsPage.java
> +    public JList<UIElement> result;
Can you choose more precise class

2021-11-25 17:54 UTC, cold-flame commented on src/test/java/com/epam/tc/hw7/MetalsAndColorsFormTest.java
> +        metalsColorsPage.form.customRadioOdd.is().selected(formData.customRadioOdd);
Use custom verify with 2 forms e.g. assertThat(Form1).isEqualTo(Form2 )

2021-11-25 17:54 UTC, cold-flame commented on src/main/java/com/epam/tc/hw7/custom/LoginForm.java
> +    @FindBy(id = "name")
Where is 'fullname' field ?

2021-11-25 20:48 UTC, lyubavinaju commented on src/main/java/com/epam/tc/hw7/custom/LoginForm.java
> +    @FindBy(id = "name")
In Header

2021-11-30 17:38 UTC, cold-flame requested changes

2021-11-30 17:38 UTC, cold-flame commented on src/main/java/com/epam/tc/hw7/entities/MetalsColorsFormData.java
> +    public String customRadioOdd;
Why you use access modifiers public for this fields? You also create methods (setters) with public access modifiers. Change public -> private for fields

2021-12-07 18:04 UTC, cold-flame approved these changes

2021-12-07 18:05 UTC, merged